### ISSUE TITLE
Error on installation with undefined function

### ISSUE THREAD

**Issue by pgrayove-mcpl** [Monroe-County-Public-Library/views_natural_sort#1]
Installing this module after the coder upgrade process causes the whole site to error out.  When I try to clear all the caches from the command line, I get the following error.

`Error: Call to undefined function entity_get_property_info() in views_natural_sort_get_supported_entity_properties() (line 498 of /app/web/modules/views_natural_sort/views_natural_sort.module).`

**Comment by laryn** [comment]
@pgrayove-mcpl Most of the regularly-used Entity API functionality was pulled into Backdrop core, but the parts that weren't are in a contrib module called "Entity Plus". There were a few spots that needed that additional functionality here. I've submitted a PR (pull request) to fix this immediate problem and should get you further along in testing. If you view the PR that is linked in the sidebar (I'll paste it below as well) you would typically first test the changes locally and if you approve them, then officially merge them into the repo using the UI.

https://github.com/Monroe-County-Public-Library/views_natural_sort/pull/2
